Ability to customize cache path and error message when not found added and readme updated
sindresorhus/run-node pull request #3
Opened 2017-10-17 18:59 UTC by joaoppsantos

* Environment variables - `RUN_NODE_ERROR_MSG` and `RUN_NODE_CACHE_PATH` - added;
* Updated readme.

2017-10-26 12:48 UTC, sindresorhus requested changes

2017-10-26 12:48 UTC, sindresorhus commented on readme.md
> +Node cache path can be customized by adding the environment variable "RUN_NODE_CACHE_PATH".
This doesn't explain what the "Node cache path" is. It's unclear what's being cached.

2017-10-26 12:48 UTC, sindresorhus commented on readme.md
> +Error message for when node ain't found can be personalized by setting the environment variable "RUN_NODE_ERROR_MSG".
This needs to be written more formally. "Ain't" is not a good word to use in documentation. And it's `Node.js`, not node, or Node.

2017-10-30 17:31 UTC, joaoppsantos commented on readme.md
> +Error message for when node ain't found can be personalized by setting the environment variable "RUN_NODE_ERROR_MSG".
Is the following sentence more appropriate ?

Ìn case there is preference for a personalized error message (e.g. `Node.js` is not found in the system), you can have one by setting the environment variable "RUN_NODE_ERROR_MSG".

2017-10-30 17:31 UTC, joaoppsantos commented on readme.md
> +Node cache path can be customized by adding the environment variable "RUN_NODE_CACHE_PATH".
This makes it more explicit ? 

In the other hand, if your desire is to customize the cache (temporary storage) path for the `Node.js` binary, you can do it by adding the environment variable "RUN_NODE_CACHE_PATH".

2017-10-30 17:33 UTC, joaoppsantos commented
Sorry the time I took to answer. Had the comments in Pending status and only noticed it now, not very familiarized with Github yet.

2018-01-14 01:41 UTC, sindresorhus commented
Closing in favor of #4

2018-01-14 01:41 UTC, closed without merging